JustFly1984/react-google-maps-api

- package.json
- yarn.lock
Cannot build application on windows machines. This PR fixes the issue.
> fix build on windows machines.

- src/LoadScript.js
Always delete windows.google on unmount
> Prevent mounting LoadScript while we are unmounting previous one

- package.json
- src/LoadScript.js
- src/utils/injectscript.js
> Updated injectScript function.

- packages/react-google-maps-api/CHANGELOG.md
- packages/react-google-maps-api/src/components/addons/MarkerClusterer.md
- packages/react-google-maps-api/src/components/addons/MarkerClusterer.tsx
- packages/react-google-maps-api/src/components/drawing/Marker.tsx
- packages/react-google-maps-api/src/index.ts
> Added MarkerClusterer support

- packages/react-google-maps-api/src/components/drawing/DrawingManager.tsx
`ondrawingManagerComplete` isn't a thing. I guess it is a typo.
> Fix onPolygonComplete event

- packages/react-google-maps-api-gatsby-example/src/examples/example-heatmap.js
- packages/react-google-maps-api/src/GoogleMap.tsx
- packages/react-google-maps-api/src/components/addons/MarkerClusterer.md
- packages/react-google-maps-api/src/components/addons/MarkerClusterer.tsx
- packages/react-google-maps-api/src/components/directions/DirectionsRenderer.tsx
- packages/react-google-maps-api/src/components/dom/OverlayView.tsx
- packages/react-google-maps-api/src/components/drawing/Circle.tsx
- packages/react-google-maps-api/src/components/drawing/Data.tsx
- packages/react-google-maps-api/src/components/drawing/DrawingManager.tsx
- packages/react-google-maps-api/src/components/drawing/InfoWindow.tsx
- packages/react-google-maps-api/src/components/drawing/Marker.tsx
- packages/react-google-maps-api/src/components/drawing/Polygon.tsx
- packages/react-google-maps-api/src/components/drawing/Polyline.tsx
- packages/react-google-maps-api/src/components/drawing/Rectangle.tsx
- packages/react-google-maps-api/src/components/heatmap/HeatmapLayer.md
- packages/react-google-maps-api/src/components/heatmap/HeatmapLayer.tsx
- packages/react-google-maps-api/src/components/kml/KmlLayer.md
- packages/react-google-maps-api/src/components/kml/KmlLayer.tsx
- packages/react-google-maps-api/src/components/maps/TrafficLayer.tsx
- packages/react-google-maps-api/src/components/overlays/GroundOverlay.tsx
- packages/react-google-maps-api/src/components/places/Autocomplete.tsx
- packages/react-google-maps-api/src/components/places/StandaloneSearchBox.md
- packages/react-google-maps-api/src/components/places/StandaloneSearchBox.tsx
- packages/react-google-maps-api/src/components/streetview/StreetViewPanorama.tsx
- packages/react-google-maps-api/src/docs/ScriptLoaded.tsx
- packages/react-google-maps-api/src/docs/googleMapKey.ts
- packages/react-google-maps-api/src/utils/helper.ts
> Fix broken initial prop apply + fix some docs examples

- packages/react-google-maps-api/.eslintrc.js
- packages/react-google-maps-api/jest.config.js
- packages/react-google-maps-api/package.json
- packages/react-google-maps-api/src/__tests__/components/circle.test.tsx
- packages/react-google-maps-api/src/components/drawing/Circle.tsx
- packages/react-google-maps-api/src/setup-tests.js
- packages/react-google-maps-api/tsconfig.json
- packages/react-google-maps-api/yarn.lock
> Setup jest infra and first tests

- packages/react-google-maps-api/src/components/drawing/Marker.tsx
> Marker.draggable is boolean

- packages/react-google-maps-api/src/index.ts
- packages/react-google-maps-api/src/map-context.ts
To be able to access map instance in other components for eg. panning needs.
> Export useGoogleMap hook

- packages/react-google-maps-api/src/LoadScript.tsx
> Update LoadScriptProps to reflect optionals

- packages/react-google-maps-api-gatsby-example/src/components/bootstrap.css
- packages/react-google-maps-api-gatsby-example/src/components/footer.js
- packages/react-google-maps-api-gatsby-example/src/components/styles.css
> Font Color Contrast Update

- packages/react-google-maps-api/src/utils/instance-persistance.ts
Fix for #117 , @JustFly1984 can you take look?
> #117 Fix map persisted instance.

- .gitignore
- .prettierrc
- README.md
- package.json
- packages/react-google-maps-api-storybook/README.md
- packages/react-google-maps-api-storybook/src/GoogleMap.stories.js
cleanup & simplify cli commands
> chor: cleanup & simplify cli commands

- package.json
- packages/react-google-maps-api/src/LoadScript.tsx
innerText undefined check in slice method
> innerText undefined check in slice method

- packages/react-google-maps-api/src/useLoadScript.md
Change the "=" to ":" within the useLoadScript parameter
> Fixes docs example in useLoadScript

- packages/react-google-maps-api-marker-clusterer/src/Clusterer.tsx
Default image path url is broken!
Replaced it with the one justfly used in an example project.
> fix broken url

- packages/react-google-maps-api/src/components/distance-matrix/DistanceMatrixService.tsx
- packages/react-google-maps-api/src/index.ts
This is the same as DirectionsService
[docs](https://developers.google.com/maps/documentation/javascript/distancematrix)
> Added Distance Matrix API

- packages/react-google-maps-api-gatsby-example/package.json
- packages/react-google-maps-api-marker-clusterer/package.json
- packages/react-google-maps-api-storybook/package.json
- packages/react-google-maps-api/package.json
- yarn.lock
Update webpack, fix & update storybook.
> fix: fix storybook updated webpack.

- packages/react-google-maps-api/src/GoogleMap.tsx
- packages/react-google-maps-api/src/components/addons/MarkerClusterer.tsx
- packages/react-google-maps-api/src/components/directions/DirectionsRenderer.tsx
- packages/react-google-maps-api/src/components/directions/DirectionsService.tsx
- packages/react-google-maps-api/src/components/distance-matrix/DistanceMatrixService.tsx
- packages/react-google-maps-api/src/components/drawing/Circle.tsx
- packages/react-google-maps-api/src/components/drawing/Data.tsx
- packages/react-google-maps-api/src/components/drawing/DrawingManager.tsx
- packages/react-google-maps-api/src/components/drawing/InfoWindow.tsx
- packages/react-google-maps-api/src/components/drawing/Marker.tsx
- packages/react-google-maps-api/src/components/drawing/Polygon.tsx
- packages/react-google-maps-api/src/components/drawing/Polyline.tsx
- packages/react-google-maps-api/src/components/drawing/Rectangle.tsx
- packages/react-google-maps-api/src/components/heatmap/HeatmapLayer.tsx
- packages/react-google-maps-api/src/components/kml/KmlLayer.tsx
- packages/react-google-maps-api/src/components/maps/BicyclingLayer.tsx
- packages/react-google-maps-api/src/components/maps/TrafficLayer.tsx
- packages/react-google-maps-api/src/components/overlays/GroundOverlay.tsx
- packages/react-google-maps-api/src/components/places/Autocomplete.tsx
- packages/react-google-maps-api/src/components/places/StandaloneSearchBox.tsx
- packages/react-google-maps-api/src/components/streetview/StreetViewPanorama.tsx
- packages/react-google-maps-api/src/components/streetview/StreetViewService.tsx
- MarkerClusterer
- Circle
- DrawingManager
- Data
- Polygon
- Polyline
- Rectangle
- Marker
- StreetViewService
- StreetViewPanorama
- StandaloneSearchBox
- Autocomplete
- GroundOverlay
- TrafficLayer
- BicyclingLayer
- KmlLayer
- HeatMapLayer
- DistanceMatrixService
- DirectionsService
- DirectionsRenderer
- Map
- InfoWindow
> Issue 178 docs description

- packages/react-google-maps-api-marker-clusterer/src/ClusterIcon.tsx
I added `alt` attribute to the cluster.
> add alt attribute to cluster image

- packages/react-google-maps-api/src/components/places/Autocomplete.md
> Fix autocomplete onPlaceChange not working in docs

- packages/react-google-maps-api-storybook/README.md
Just correcting a wrong word in Storybook README
> fix: text in storybook's readme

- README.md
> feat: add badges to readme

- packages/react-google-maps-api/src/components/dom/OverlayView.tsx
- packages/react-google-maps-api/src/components/dom/dom-helper.ts
> Fix OverlayView props ts definition

- packages/react-google-maps-api/src/components/addons/InfoBox.tsx
- packages/react-google-maps-api/src/components/dom/OverlayView.tsx
- packages/react-google-maps-api/src/components/drawing/InfoWindow.tsx
Made tsdx be able to guess the global variable for react-dom is "ReactDOM". 
Issue: https://github.com/JustFly1984/react-google-maps-api/issues/295#issuecomment-559604550
> Fixed the global.reactDom problem

- packages/react-google-maps-api/src/components/streetview/StreetViewService.tsx
> Fix #446 - street view service onLoad not being called on mount

- packages/react-google-maps-api/README.md
This is a great library, and we're using it to display all of our network nodes on our map. We'll be using this tool as long as we use Google Maps :)
> Add NYC Mesh to the README as a user of the library

- packages/react-google-maps-api/src/components/dom/OverlayView.tsx
Fixes #198 
This PR removes `appendChild` in `OverlayView.draw` method.
DOM manipulation is delegated to React with this PR, so performance of re-drawing OverlayView increases.
> Remove appendChild in OverlayView.draw method

- packages/react-google-maps-api/CHANGELOG.md
Update CHANGELOG regarding #871
> Update v1.9.0 CHANGELOG 

- package.json
> Add zpirme0920 in contributors list

- packages/react-google-maps-api/src/components/dom/dom-helper.ts
This should fix open issue #1090 and prevent it from ever happening again
> added check for mapcanvasprojection in dom helpers

- packages/react-google-maps-api-marker-clusterer/.eslintrc.js
- packages/react-google-maps-api-marker-clusterer/.prettierrc.js
- packages/react-google-maps-api-marker-clusterer/src/Clusterer.tsx
- packages/react-google-maps-api-marker-clusterer/tsconfig.json
- packages/react-google-maps-api/src/components/addons/MarkerClusterer.md
also fix formating for files that weren't formatted with prettier
> amend docs for MarkerClusterer

- packages/react-google-maps-api/src/components/drawing/Marker.tsx
Fixes #1848
This converts `this.state.marker` to `this.marker` in Marker.tsx.
> fix: Correctly remove markers when unmounting a Marker.

- packages/react-google-maps-api/src/components/kml/KmlLayer.tsx
> Make onLoad and onUnmount callbacks for KMLLayer optional

- packages/react-google-maps-api-gatsby-example/src/components/google-maps.js
This PR fixes the Gatsby Example. Fixes #2934
> fix: gatsby example maps

- packages/react-google-maps-api/package.json
- packages/react-google-maps-api/src/components/maps/BicyclingLayer.tsx
> fix bicycling layer error

- ISSUE_TEMPLATE.md
Improving language of the template.
The English used needed adjusting.
> Improving English

- packages/react-google-maps-api/README.md
Due to some confusion about this sample code going to coordinate (0,0), this should at least keep us on land.
> Update Readme example

- packages/react-google-maps-api/src/components/overlays/GroundOverlay.tsx
added `google.maps.LatLngBoundsLiteral | google.maps.LatLngBounds `
> fixed interface GroundOverlayProps

- .storybook/googlemapsReactWrapperDecorator.tsx
- packages/react-google-maps-api/src/components/dom/Overlay.tsx
- packages/react-google-maps-api/src/components/dom/OverlayView.stories.tsx
- packages/react-google-maps-api/src/components/dom/OverlayView.tsx
- packages/react-google-maps-api/src/index.ts
Added OverlayViewF as  Functional Component. Adapted code from Daw-Chih Liou blog post.
Fixes #3080
> Added OverlayViewF as a Functional Component

- packages/react-google-maps-api/src/GoogleMap.tsx
- packages/react-google-maps-api/src/components/drawing/Circle.tsx
- packages/react-google-maps-api/src/components/drawing/Marker.tsx
- packages/react-google-maps-api/src/components/drawing/Polyline.tsx
- packages/react-google-maps-api/src/components/drawing/Rectangle.tsx
map listenner is not updated because onDblClick is specified in the dependency of onDragEnd.
Fixed onDragEnd's useEffect dependency to specify onDragEnd
> Fix onDragEnd useEffect dependency

- packages/react-google-maps-api/src/components/addons/MarkerClusterer.tsx
- packages/react-google-maps-api/src/components/addons/MarkerClustererF.stories.tsx
- packages/react-google-maps-api/src/index.ts
Added missing functional component for Clusterer class for React 18 support.
> added functional component for Clusterer class

- packages/react-google-maps-api-infobox/package.json
- packages/react-google-maps-api-marker-clusterer/package.json
- packages/react-google-maps-api/package.json
- packages/react-google-maps-api/yarn.lock
- yarn.lock
I've removed type=module from package.json since it broke build.
I've reverted updates to googlemaps packages, since they broke clusterer (the position of the clusters moved around with dragging and was positioned wrong).
> Reverted package.json lines to fix broken build

- packages/react-google-maps-api/src/components/heatmap/HeatmapLayer.tsx
- packages/react-google-maps-api/src/index.ts
This PR adds a functional component version of HeatmapLayer
> Add HeatmapLayerF component

- packages/react-google-maps-api/src/components/overlays/GroundOverlay.tsx
- packages/react-google-maps-api/src/index.ts
Currently there isn't a functional version of GroundOverlay. I've made something small for the interm for my needs, but having a fully featured component would be awesome!
Thank you!
> Added functional GroundOverlayF

- packages/react-google-maps-api/README.md
Hey all,
When checking out the links to see how others have used this project, I noticed that the two removed below were dead links. The first one appears particularly dangerous.
Thanks!
> Removing dead links from NPM Readme.md

- .storybook/main.js
- README.md
- lerna.json
- packages/react-google-maps-api-gatsby-example/yarn.lock
- packages/react-google-maps-api-infobox/yarn.lock
- packages/react-google-maps-api-marker-clusterer/yarn.lock
- packages/react-google-maps-api/yarn.lock
- Adds configFile and baseUrl config to tsconfig-paths-webpack-plugin in .storybook/main.js
- Sets yarn as npmClient in lerna.json
- Fixes invalid yarn.lock files
- Adds yarn bootstrap instruction to local develop instructions in readme
Problems with initial project setup.
> Fixes issues with project setup related to storybook and lerna

- packages/react-google-maps-api/src/components/drawing/Marker.tsx
Please refer to GitHub issue #3247.
> fix marker animations not being cleared

- packages/react-google-maps-api-gatsby-example/src/examples/example-directions.tsx
> fix Directions API example

- packages/react-google-maps-api/src/components/directions/DirectionsRenderer.md
Fix the Directions Callback in the Docs
Related to: https://github.com/JustFly1984/react-google-maps-api/pull/3266, https://github.com/JustFly1984/react-google-maps-api/issues/3256, https://github.com/JustFly1984/react-google-maps-api/issues/3261
> [Fix][Ezra] Directions Docs Callback Fix

- ISSUE_TEMPLATE.md
Update the issue template to include information about the current state of the project.
https://github.com/JustFly1984/react-google-maps-api/issues/3300
> Add information about the state of the project to issue template

- packages/react-google-maps-api/src/components/drawing/Polygon.tsx
This fixes this issue: https://github.com/JustFly1984/react-google-maps-api/issues/3374 and applies a similar solution that @jwalton had come up with for the Marker issue: https://github.com/JustFly1984/react-google-maps-api/issues/1848.
This allows the Polygon to properly unmount and sets a map reference on the polygon.
> fix: alter state to allow polygon to tear down on unmount, setMap reference on polygon
