JustFly1984/react-google-maps-api

packages/react-google-maps-api/package.json
Fixes #57 so that consumers have access to googlemaps types in IDE.
=> Move @types/googlemaps to be a direct dependency

packages/react-google-maps-api/src/components/addons/MarkerClusterer.tsx, packages/react-google-maps-api/src/components/directions/DirectionsRenderer.tsx, packages/react-google-maps-api/src/components/directions/DirectionsService.tsx, packages/react-google-maps-api/src/components/drawing/Circle.tsx, packages/react-google-maps-api/src/components/drawing/DrawingManager.md, packages/react-google-maps-api/src/components/drawing/DrawingManager.tsx, packages/react-google-maps-api/src/components/drawing/InfoWindow.tsx, packages/react-google-maps-api/src/components/drawing/Marker.tsx, packages/react-google-maps-api/src/components/drawing/Polygon.tsx, packages/react-google-maps-api/src/components/drawing/Polyline.tsx, packages/react-google-maps-api/src/components/drawing/Rectangle.tsx, packages/react-google-maps-api/src/components/heatmap/HeatmapLayer.tsx, packages/react-google-maps-api/src/components/kml/KmlLayer.tsx, packages/react-google-maps-api/src/components/maps/BicyclingLayer.tsx, packages/react-google-maps-api/src/components/maps/TrafficLayer.tsx, packages/react-google-maps-api/src/components/overlays/GroundOverlay.tsx, packages/react-google-maps-api/src/components/places/Autocomplete.tsx, packages/react-google-maps-api/src/components/places/StandaloneSearchBox.tsx, packages/react-google-maps-api/src/components/streetview/StreetViewPanorama.tsx, packages/react-google-maps-api/src/components/streetview/StreetViewService.tsx, packages/react-google-maps-api/src/docs/googleMapKey.ts, packages/react-google-maps-api/src/utils/helper.ts
setState callback is called after componentDidUpdate. In CDU we register event handlers, but in setState callback we don't clean them up. This causes event handlers to be registered twice, thus firing twice. 
Since CDU will always run before the setState callback, there's no need to register events in the callback.
We should probably even go a step further and initialise the state in the constructor. Any side effects should be moved to CDU. This will prepare us for moving to using hooks..
=> Fixed #79 - event handlers firing twice

packages/react-google-maps-api/src/GoogleMap.tsx, packages/react-google-maps-api/src/LoadScript.tsx, packages/react-google-maps-api/src/components/addons/MarkerClusterer.tsx, packages/react-google-maps-api/src/components/directions/DirectionsRenderer.tsx, packages/react-google-maps-api/src/components/directions/DirectionsService.tsx, packages/react-google-maps-api/src/components/dom/OverlayView.tsx, packages/react-google-maps-api/src/components/drawing/Data.tsx, packages/react-google-maps-api/src/components/drawing/DrawingManager.tsx, packages/react-google-maps-api/src/components/drawing/InfoWindow.tsx, packages/react-google-maps-api/src/components/drawing/Marker.tsx, packages/react-google-maps-api/src/components/drawing/Polygon.tsx, packages/react-google-maps-api/src/components/drawing/Polyline.tsx, packages/react-google-maps-api/src/components/drawing/Rectangle.tsx, packages/react-google-maps-api/src/components/heatmap/HeatmapLayer.tsx, packages/react-google-maps-api/src/components/kml/KmlLayer.tsx, packages/react-google-maps-api/src/components/maps/BicyclingLayer.tsx, packages/react-google-maps-api/src/components/maps/TrafficLayer.tsx, packages/react-google-maps-api/src/components/overlays/GroundOverlay.tsx, packages/react-google-maps-api/src/components/places/Autocomplete.tsx, packages/react-google-maps-api/src/components/places/StandaloneSearchBox.tsx, packages/react-google-maps-api/src/components/streetview/StreetViewPanorama.tsx, packages/react-google-maps-api/src/components/streetview/StreetViewService.tsx, packages/react-google-maps-api/src/index.ts
This is super useful for any sort of wrapping. Simplified example...
```tsx
interface IProps extends GoogleMapProps {
model: TMapModel
}
const BaseMap: React.FC<IProps> = ({ model, ...mapProps }) => {
<LoadScript ...>
<GoogleMap {...model.mapProps} {...mapProps}>{children}</GoogleMap>
</LoadScript>
}
```
=> Export props interfaces

packages/react-google-maps-api/package.json
This is a totally bad idea to rely on a specific version of React types. In a moment you have two separate versions in a project, things get really wonky and those types are conflicting with each other.
I would generally say that any @types does not belong to package dependencies, but google maps related ones are ok because you don't usually have those installed for any other reason. The one for `invariant` shouldn't be there also imo because it's not a part of public API.
=> React types as a peer dependency

packages/react-google-maps-api/src/LoadScript.tsx
https://developers.google.com/maps/documentation/javascript/localization
> By default, the Maps JavaScript API uses the user's preferred language setting as specified in the browser,
https://developers.google.com/maps/documentation/javascript/versions
> If you do not explicitly specify a channel or version, you will receive the weekly channel by default.
> For most applications, we recommend the weekly channel. This is the most current and up-to-date version and contains the latest bug fixes and performance improvements.
=> Require less props for LoadScript

package.json, packages/react-google-maps-api/package.json, packages/react-google-maps-api/src/LoadScript.tsx, packages/react-google-maps-api/src/__tests__/utils/helper.test.ts, packages/react-google-maps-api/src/components/drawing/InfoWindow.tsx, packages/react-google-maps-api/src/utils/helper.ts, packages/react-google-maps-api/yarn.lock, yarn.lock
Fixes #94 - anchor should not be required by InfoWindow
Fixes #96 Fixes typescript error by removing react typings from peer dependencies (they're not needed there)
Fixes typescript error in LoadScript (caused by default props + interface definitions)
=> Version 1.2.3-alpha.1

packages/react-google-maps-api/package.json, packages/react-google-maps-api/yarn.lock
These packages do not need to be peerDependencies as we do not care if the package consumer has them installed (they might not even be using typescript)
=> Removed @types/react and @types/react-dom as peerDependencies

packages/react-google-maps-api-marker-clusterer/package.json, packages/react-google-maps-api/package.json
It's necessary for node based environments, eg. testing
=> Add main field to package.json

packages/react-google-maps-api/src/components/dom/OverlayView.tsx
https://spectrum.chat/react-google-maps/general/overlayview-position-is-not-updated~3a32f12a-b909-4316-af7a-cd6f9a92ed8c
Unfortunately, I was not able to test it out, build is failing for me with bunch of TS errors.
=> fix(api): Redraw OverlayView on position or bounds change

packages/react-google-maps-api/src/components/dom/OverlayView.tsx
As much as awkward this looks, it seems that on some occasion the `draw` is called before the `onAdd` causing the error. It seems to be able to recover itself with a next draw, but it's kinda spamming our bug reporting service.
> Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'
=> [OverlayView] Add check for containerElement

packages/react-google-maps-api/src/GoogleMap.tsx
Added 2 new event from the native events list of Google maps.
Those 2 new events add the opportunity to the user to listen at the mouse down and mouse up events.
Can help to create a method to manage long click on mobile devices.
=> Added two new mouse Events to help on mobile devices

packages/react-google-maps-api-marker-clusterer/package.json
My mistake just noticed it ... https://unpkg.com/@react-google-maps/marker-clusterer@1.2.4
=> Correct clusterer main fields

packages/react-google-maps-api/src/GoogleMap.md, packages/react-google-maps-api/src/components/directions/DirectionsRenderer.md, packages/react-google-maps-api/src/components/dom/OverlayView.md, packages/react-google-maps-api/src/components/drawing/Circle.md, packages/react-google-maps-api/src/components/drawing/Data.md, packages/react-google-maps-api/src/components/drawing/DrawingManager.md, packages/react-google-maps-api/src/components/drawing/InfoWindow.md, packages/react-google-maps-api/src/components/drawing/Marker.md, packages/react-google-maps-api/src/components/drawing/Polygon.md, packages/react-google-maps-api/src/components/drawing/Polyline.md, packages/react-google-maps-api/src/components/drawing/Rectangle.md, packages/react-google-maps-api/src/components/heatmap/HeatmapLayer.md, packages/react-google-maps-api/src/components/kml/KmlLayer.md, packages/react-google-maps-api/src/components/maps/BicyclingLayer.md, packages/react-google-maps-api/src/components/maps/TrafficLayer.md, packages/react-google-maps-api/src/components/overlays/GroundOverlay.md, packages/react-google-maps-api/src/components/places/Autocomplete.md, packages/react-google-maps-api/src/components/places/StandaloneSearchBox.md, packages/react-google-maps-api/src/components/streetview/StreetViewPanorama.md, packages/react-google-maps-api/src/components/streetview/StreetViewService.md, packages/react-google-maps-api/src/docs/ScriptLoaded.tsx, packages/react-google-maps-api/src/docs/getting-started.md, packages/react-google-maps-api/src/docs/introduction.md
* Added short documentation about `useGoogleMap` existence.
* Removed double titles for Introduction & Getting started.
Also fixed interactive examples which were being displayed like this...
For some reason, it auto-imports component being shown so it fails. See the [build preview](https://5cfa2fd986ea9a00084f529b--react-google-maps-api-docs.netlify.com/#directionsrenderer) for comparison.
=> Improve docs

package.json, packages/react-google-maps-api-gatsby-example/.eslintignore
Fixes #147 
I've also included root script `start:gatsby` that builds both dependents packages just to be sure. Since TSDX keep a cache, it shouldn't take much longer to build these repeatedly.
Eventually, some watch mode (available in TSDX) could be added if a need arise.
=> Running Gatsby locally

packages/react-google-maps-api/src/LoadScript.tsx, packages/react-google-maps-api/src/LoadScriptNext.md, packages/react-google-maps-api/src/LoadScriptNext.tsx, packages/react-google-maps-api/src/index.ts, packages/react-google-maps-api/src/useGoogleMap.md, packages/react-google-maps-api/src/useLoadScript.md, packages/react-google-maps-api/src/useLoadScript.ts, packages/react-google-maps-api/src/useLoadScript.tsx, packages/react-google-maps-api/src/utils/make-load-script-url.ts, packages/react-google-maps-api/styleguide.config.js
Fixes #139 
As noted in #139, instead of modifying current LoadScript I have created an alternative approach with Hooks and without that cleanup logic which I think was causing more issues than it helped.
I've added this build into our app and so far it works correctly and intend to push it to the production soon (yes, I am that bold) so we will see if it actually helps.
I've also decided to keep whole logic in the `useLoadScript` hook instead of a component to provide loading state directly instead of the callback. This is the way I am using it and works great. 
```tsx
export const BaseMap = observer<IBaseMapProps>(
({ model, children }) => {
const { user } = useRoot()
const { isLoaded } = useLoadScript({
id: 'script-loader',
version: 'weekly',
googleMapsApiKey: appConfig.googleMapsApi!, …
```
=> Add useLoadScript and LoadScriptNext

packages/react-google-maps-api/README.md
Added note and link to Spectrum help community. Noted that React v16.8+ required for latest features including hooks.
=> README tweak: Spectrum community, React 16.8 if you want hooks

packages/react-google-maps-api/src/useLoadScript.md
RE: https://spectrum.chat/react-google-maps/general/useloadscript-documentation-error~d200df47-85b7-4e4f-9126-402f96d10199
=> Tiny typo fix

packages/react-google-maps-api/src/utils/helper.ts
current  - Events are unregistered, then updates are applied, then evens are re-registered
This causes a bug that if an update needs to cause an event call, that event isn't registered at the time of the update. (as seen in #182)
Switching the order solves this issue
=> Fixed #182 - onOverlayComplete not called 

packages/react-google-maps-api/src/utils/injectscript.ts
Currently if the id remains constant and the url change, the older script will remain loaded and the new one will not replace the old one. If I just change the lib language, I expect the script to reload with the new language, without having to deal with creating a different id to force a reload.
cc @JustFly1984 @FredyC
Related:
- https://github.com/JustFly1984/react-google-maps-api/issues/186
- https://github.com/JustFly1984/react-google-maps-api/pull/188
- https://github.com/JustFly1984/react-google-maps-api/pull/189
=> injectScript should recreate the script if the url changes

packages/react-google-maps-api/src/utils/injectscript.ts, packages/react-google-maps-api/src/utils/make-load-script-url.ts
According #184 
`onload` of `script` DOM will be call after the script is loaded.
However it doesn't mean that `google` is ready to be used in your app.
According Google Map Javascript document, it recommends to be use `callback` function to continue the process after `google` is ready.
In this PR, I created `initMap` function as global function for make it resolve script after `google` is ready in your app.
=> Use callback instead of onload to resolve injectScript as loaded!

packages/react-google-maps-api/src/__tests__/utils/injectscript.test.ts, packages/react-google-maps-api/src/utils/injectscript.ts, packages/react-google-maps-api/src/utils/make-load-script-url.ts
When injectScript runs it checks for the presence of a script element with matching ID in the DOM. If it finds it, it immediately resolves, regardless of whether the script has finished loading or not.
This changes add a 'state' attribute to the script that can be used to check if the google maps is ready or not and then use that information to decide whether to resolve immediately.
There are a couple of possible issues. I would probably prefer using `script.addEventListener('load', callback)` instead of `script.onload` and then using the closure to maintain a reference back to the original call to injectScript's onload callback. That's just what I prefer but attempting with changing the source as little as possible to implement the feature.
I have seen in other threads the mention of …
=> in injectScript don't immediately resolve if matching script is in the dom

packages/react-google-maps-api-marker-clusterer/package.json, packages/react-google-maps-api/package.json
@JustFly1984 Latest TSDX doesn't build UMD by default, so it needs to be specified. This is the fix for https://github.com/JustFly1984/react-google-maps-api/pull/194#issuecomment-516860162
=> Build UMD too

packages/react-google-maps-api-marker-clusterer/package.json, packages/react-google-maps-api/package.json
Discovered another build related issue, we were referring to old files. TSDX has changed the way how are output files named slightly. I've also added cleanup of dist before build to avoid having old code in there.
To explain the ESM format, there is no longer dev/prod variant as that's up to the consumer. It was actually an issue in this project that has lead me to [discover the problem](https://github.com/palmerhq/tsdx/issues/140).
cc @JustFly1984 @uriklar
=> Fix paths for built files

packages/react-google-maps-api/src/useLoadScript.tsx, packages/react-google-maps-api/src/utils/make-load-script-url.ts
At the moment it is not possible to add a channel parameter to the maps url by passing it as a prop to `LoadScript`/`useLoadScript`. Channels allow for tracking of usage across different applications using the same client ID. See [Google Maps docs](https://developers.google.com/maps/premium/reports/usage-reports#channels).
=> Allow for adding a channel to the maps url

packages/react-google-maps-api/src/components/addons/InfoBox.md
The example for the `InfoBox` component in docs was broken due to a missing import.
=> Fix broken InfoBox import in docs

packages/react-google-maps-api/src/components/drawing/Data.md
Using the string `'TOP_LEFT'` as the value for `controlPosition` of `Data` produces this error: `InvalidValueError: setControlPosition: TOP_LEFT`.
Changed that to just use the actual value from google maps, but had to wrap it in a condition because `window.google` started out as `undefined`.
=> Fix using 'TOP_LEFT' as controlPosition in Data docs

packages/react-google-maps-api/src/components/drawing/Marker.tsx
It should be `google.maps.MarkerOptions` not `google.maps.MapOptions`
=> fix(Marker): correct options type

packages/react-google-maps-api/src/GoogleMap.tsx
The panTo() function has the purpose of centering a position smoothly. 
I am not sure if it is best to use "this.getInstance()" or "this.state.map" as input parameter to the "map.panTo()" function. I have used "this.getInstance()" for now. 
At the moment there is no function that centers a pin/position on the map smoothly.
It is possible to center a pin, but not with a smooth animation - which is included in the panTo() function.
=> panTo() function. Centering map smoothly.

packages/react-google-maps-api-infobox/src/InfoBox.tsx
As mentioned in https://spectrum.chat/react-google-maps/general/infobox-doesnt-react-to-options-change~fc8e01bd-3d2a-485c-880d-4a5002a13481, infobox didn't react to options changes. This quickfix solves the issue.
=> fix infobox extend function

packages/react-google-maps-api/src/utils/injectscript.ts
Currently, only the first `onerror` callback is called when a script fails to load. This pull request just uses a closure to be able to recursively call all `onerror` callbacks in the same way that the `initMap` callbacks are recursively called
=> Ensure that all onerror callbacks are called on a script load error

packages/react-google-maps-api/src/utils/injectscript.ts
I realised that I forgot to put this important line into my previous commit. Sorry for making this be split over two releases now 🙈 
After logging the error from inject script ensure that we rethrow the original error so that any promises chain outside of the `injectScript` function is still able to catch the error and handle it according to their own logic. Specifically used in useLoadScript hook. Which, without this fix always assumes that the script loads and then error when trying to access `window.google.maps`
=> after logging the error from inject script rethrow it

packages/react-google-maps-api/src/components/places/Autocomplete.tsx
I want to use this project in a production app, so I was looking at docs and noticed that `onLoad` and `onUnmount` have their comments interchanged.
=> docs(places): fix comments for onLoad, onUnmount

packages/react-google-maps-api/src/LoadScript.tsx
Minor spelling mistake corrected in one of the warning messages in LoadScript component.
=> Corrected spelling mistake for warning message.

packages/react-google-maps-api/src/utils/injectscript.ts
Fixes #282 
when loading fails, we represent that inside the data-state attribute.
=> #282, re-inject script when data-state is in an error state

packages/react-google-maps-api/README.md
Converted an old hobby project from AngularJS to React during the holiday season. Wanted a good Google Maps library to do so: After a bit of digging, `@react-google-maps/api` felt like the best alternative.
If you want examples of websites that use this library, here's one more. Thanks for making using Google Maps with React so convenient.
=> Added Shipwrecks.cc as an example of a site that uses @react-google-maps/api

packages/react-google-maps-api/src/GoogleMap.tsx
I saw that the documentation for two of the GoogleMap props was mixed up.
=> Documentation for two functions was mixed up

packages/react-google-maps-api/package.json
PR is to address this issue https://github.com/JustFly1984/react-google-maps-api/issues/430
=> Delete `engines` from `package.json`

packages/react-google-maps-api/src/components/addons/MarkerClusterer.md
Updated MarkerClusterer.md to not use the index as a key. There is an eslint rule for this
https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-array-index-key.md. 
The clustering will not work properly on updates unless you use a key such as maybe the latitude + longitude. I spent a lot of time trying to figure out why the updates were not creating the clusters properly.
=> Update MarkerClusterer.md to not use index as key

packages/react-google-maps-api/src/docs/getting-started.md
Great job, buddies! :star2: It's been hard to find a maintained library for integrating Google Maps into a React application.
I took the opportunity to add a few changes in the _Getting Started_ section.
Without these properties, we can't see either anything on the screen nor any error message. It might confuse both beginners and even experienced developers.
This PR helps to add the basic props in order to get a functional rendered map on the screen. The users can start working from this point.
In order to have the simplest form, I also removed the `id` props as they seem to be not really required (at least not to get a functional map).
=> docs(api): add needed props to get a functional rendered map

packages/react-google-maps-api/src/components/maps/TrafficLayer.tsx, packages/react-google-maps-api/src/components/overlays/GroundOverlay.tsx, packages/react-google-maps-api/src/components/places/StandaloneSearchBox.tsx, packages/react-google-maps-api/src/components/streetview/StreetViewPanorama.tsx, packages/react-google-maps-api/src/components/streetview/StreetViewService.tsx
Just noticed that the load and unmount documentation was switched around in some places.
=> Fix load/unmount documentation switch

packages/react-google-maps-api/src/index.ts
By exporting the `MapContext` it is possible to lift the context of the map up, allowing components to render map components without being a child of the `GoogleMap` component.
```tsx
...
const [myMap, setMyMap] = useState(null)
return (
<Content>
<GoogleMap onLoad={setMyMap} />
<MapContext.provider value={myMap}>
<Sidebar>
<MyMarker />
</SideBar>
</MapContext>
</Content>
)
...
```
This is currently very clunky to do, as you would have to save the map instance in a state and pass your own context around. But since the map components are looking for the `MapContext` by default, you would have to do something like
```tsx
<Marker onLoad={m => map && m.setMap(map)} />
```
This was discussed a bit here as well: https://github.com/JustFly1984/react-google-maps-api/issues/49
An alternative to …
=> Export map context

packages/react-google-maps-api-marker-clusterer/src/Cluster.tsx, packages/react-google-maps-api-marker-clusterer/src/Clusterer.tsx
Based on https://github.com/googlemaps/v3-utility-library/pull/613
I was using your library, with the clusterer, with lots of pins (around 10,000) and I noticed some slow behaviour when changing zoom levels. You could see all the clusters get built back up. I didn't see this with a different version of the clusterer, so I dug in and I found that that the original repo for the Google clusterer had a bugfix to only re-render the clusters at the end of clustering. This PR just pulls in that fix.
=> Re-render icons on end of clustering cycle. 

packages/react-google-maps-api/src/components/drawing/Marker.tsx, packages/react-google-maps-api/src/types.tsx
This is to resolve https://github.com/JustFly1984/react-google-maps-api/issues/10
It allows putting an InfoWindow as a child of a Marker, and having the infowindow automatically anchored to the marker.
=> Anchoring InfoWindow children of Markers

packages/react-google-maps-api/src/components/dom/OverlayView.tsx
Fixes #875 
This PR fixes typical bugs in [OverlayView#componentDidUpdate](https://github.com/JustFly1984/react-google-maps-api/blob/master/packages/react-google-maps-api/src/components/dom/OverlayView.tsx#L131) 
It will potentially compares different types of objects and produce javascript errors like #875 .
eg) `LatLng` vs `LatLngLiteral` or `LatLngBounds` vs `LatLngBoundsLiteral` 
The changes of this pr try to solve the problem by convert literals to instance of LatLng (or LatLngBounds) then compare (toString() of instance)
=> Compare between LatLng and LatLngLiteral with proper way

packages/react-google-maps-api/src/components/dom/OverlayView.tsx
> Fixes #875
I found some mistake in prev PR #899 .
`!==` operator compares with object reference itself instead `toString()`
So, I made some modifications and tweeks for that.
Convert the coordinates(LatLng, LatLngLiteral, LatLngBounds, LatLngBoundsLitral) to strings only and use them for comparison.
Sorry for previous release(1.9.4)..  🙏
=> [OverlayView] Convert coordinates to string for comparison. Not object

packages/react-google-maps-api/src/LoadScript.tsx, packages/react-google-maps-api/src/useLoadScript.tsx, packages/react-google-maps-api/src/utils/injectscript.ts
Added support for Content Security Policy nonces. This PR makes it possible to provide a nonce to, for example, the `useLoadScript` hooks. The changes in this PR will propagate the nonce to the `injectScript` function which will load the Google Maps javascript. 
Background information: 
https://conference.hitb.org/hitbsecconf2017ams/materials/D1T1%20-%20Michele%20Spagnuolo%20and%20Lukas%20Wilschelbaum%20-%20So%20We%20Broke%20All%20CSPS.pdf
=> Added support for CSP nonces

packages/react-google-maps-api-infobox/src/InfoBox.tsx
This one-line change addresses an accessibility violation for screen readers, in that the image used for the 'x' icon in the `InfoWindow` lacks alt text. 
The alt is now an empty string due to the image being decorative rather than informative, as the image is already wrapped in a `<button>` with `aria-label="Close"`
=> Accessibility: add empty alt text to 'x' icon image in InfoWindow

packages/react-google-maps-api/src/components/places/Autocomplete.tsx
Currently the autocomplete ref is a div that is not styleable.
This changes should add this option.
Were not able to set up locally. Please test it.
Fixes #201
=> Make Autocomplete.tsx stylable

packages/react-google-maps-api/src/components/dom/OverlayView.tsx, packages/react-google-maps-api/src/components/dom/dom-helper.ts, packages/react-google-maps-api/src/types.tsx
This fixes panning re-rendering OverlayView component causing performance issues with a larger set of complex custom markers.
https://react-google-maps-api-docs.netlify.app/#overlayview
Examples in our application:
=> Position equality helper for overlayview

packages/react-google-maps-api/src/useLoadScript.tsx, packages/react-google-maps-api/src/utils/make-load-script-url.ts
Google now supports using vector maps instead of raster (in beta), see https://developers.google.com/maps/documentation/javascript/vector-map :tada: 
In order to support this, the load script url needs to include the available map ids.
Additionally, the `MapOptions` should include the specific `mapId`, however the official types are not yet updated, as evident from their own examples [here](https://github.com/googlemaps/js-samples/blob/25a4ff9635382931e19cb723b3c9460076af1d0e/samples/vector-use-static-map/src/index.ts#L43).
However, since all the option props from the `GoogleMap` component are applied, we can just use
```ts
<GoogleMap
onLoad={onMapMount}
options={{ mapId: '...' } as google.maps.MapOptions }
/>
```
and wait for the official types to get updated.
I've tested it, and it …
=> Support map ids for vector maps

packages/react-google-maps-api/package.json
Related to #1684 
It is to allow react 17 as a peer dependencies. This version of react should (in theory) not break anything. At work we are currently on react 17 and we've add no issue related to it.
=> Allow react v17 as peer dependencies

packages/react-google-maps-api/src/components/drawing/Marker.md
Issue: Documentation unclear on how to use Maker icon prop. https://github.com/JustFly1984/react-google-maps-api/issues/1555 
Solution: Update documentation to include Marker icon prop example.
Example will produce that above map/markers.
=> feat(Marker.md): add custom icon example

packages/react-google-maps-api-marker-clusterer/src/ClusterIcon.tsx, packages/react-google-maps-api-marker-clusterer/src/types.tsx
This pull request adds the ability to set the CSS class of a cluster from the cluster style.
This was modeled after the Google Maps JavaScript MarkerClustererPlus Advanced example:
- [Interactive example](https://googlemaps.github.io/js-markerclustererplus/examples/advanced_example.html)
- [Code for CSS only style](https://github.com/googlemaps/js-markerclustererplus/blob/aca45766bcb5065153592a34c3f99fa7bf5b898b/examples/advanced_example.html#L177)
Here is how the className property is [set in Google's `useStyle()`](https://github.com/googlemaps/js-markerclustererplus/blob/aca45766bcb5065153592a34c3f99fa7bf5b898b/src/cluster-icon.ts#L412).
This will allow users to have more control over the classes for each of the clusters, enabling them to use a CSS only approach to clustering.
=> Add ClusterIcon CSS Class From ClusterIconStyle

packages/react-google-maps-api-marker-clusterer/jest.config.js, packages/react-google-maps-api-marker-clusterer/package.json, packages/react-google-maps-api-marker-clusterer/src/Clusterer.tsx, packages/react-google-maps-api-marker-clusterer/src/__tests__/clusterer.test.ts, packages/react-google-maps-api-marker-clusterer/src/setup-tests.js, packages/react-google-maps-api-marker-clusterer/yarn.lock
Documentation says that for 125 markers index 3 is returned
> The styles array element used has an index of index minus 1. For example, the default calculator returns a text value of "125" and an index of **3** for a cluster icon representing 125 markers so the element used in the styles array is 2.
Unfortunately current code returns index 4
Code:
```javascript
const CALCULATOR = function CALCULATOR(
markers: MarkerExtended[],
numStyles: number
): ClusterIconInfo {
let index = 0
const title = ''
const count = markers.length.toString()
let dv: string | number = count
while (dv !== 0) {
// eslint-disable-next-line @typescript-eslint/ban-ts-ignore
// @ts-ignore
dv = parseInt(dv, 10) / 10
index++
}
index = Math.min(index, numStyles)
return {
text: count,
index: index,
title: title,
}
}
``` …
=> Fix CALCULATOR in Clusterer

packages/react-google-maps-api/src/components/drawing/Marker.md
Added an example for markers creation, without raw url. 
This example is here to show that markers can be created with React, then rendered in Google Maps
closes https://github.com/JustFly1984/react-google-maps-api/issues/2792
=> Add pure React example for marker rendering

packages/react-google-maps-api/package.json, packages/react-google-maps-api/src/components/addons/GoogleMarkerClusterer.stories.tsx, packages/react-google-maps-api/src/components/addons/GoogleMarkerClusterer.tsx, packages/react-google-maps-api/src/components/drawing/Marker.tsx, packages/react-google-maps-api/src/index.ts, packages/react-google-maps-api/yarn.lock
[@googlemaps/markerclusterer](https://github.com/googlemaps/js-markerclusterer) is an official Google library for marker clusters. According to its home page, it is a continuation of the library in this project. It looks pretty active and well maintained. Adds some new and exciting features to clusters.
It can be used as an option in this project, and the old one is kept for backward compatibility, or it can completely replace the old `MarkerClusterer` at some point.
=> Google marker clusterer

packages/react-google-maps-api-marker-clusterer/src/ClusterIcon.tsx
If I use the `setStyles` function on the clusterer, it doesn't update the ClusterIconStyle styles in the `ClusterIcon`. After each `clusteringend`, `updateIcon` is ran on each cluster but not with the current ClusterIconStyle styles array. It is ran with the styles array from initialization. 
This fix gets the current styles array from the clusterer when `useStyle` is called. 
Note: assigning `this.className = ${this.className} ${style.className}` would double up classNames since this.className is no longer just the default cluster className. So I added a clusterClassName prop.
I'm trying to update the Styles at `clusteringend`. I want to edit the `className` of the `ClusterIcon` based on the markers in the cluster. So I have to wait until the clustering ends to get the markers in each …
=> FIX: Allow useStyle (and updateIcon) to use current styles object

packages/react-google-maps-api/src/GoogleMap.tsx
Events are already defined at:
https://github.com/JustFly1984/react-google-maps-api/blob/1c5a2a7d24f916000ac09ce07c2cf6edcc9168bb/packages/react-google-maps-api/src/GoogleMap.tsx#L15-L16
I'm not sure why, mousedown, mouseup events are not documented on Map instance at https://developers.google.com/maps/documentation/javascript/reference/map?hl=en#Map-Events, but they work (tested).
=> Add onMouseDown, onMouseUp event props

packages/react-google-maps-api-marker-clusterer/src/ClusterIcon.tsx, packages/react-google-maps-api/src/components/addons/MarkerClusterer.stories.tsx
@JustFly1984 We use a strict CSP policy. The policy doesn't allow inline CSS. This prevents us from using the `ClusterIcon` component because the `show` method uses `innerHTML` _with styles in the injected markup_. This PR's rewrites the the `show` method and removes the problematic `innerHTML` with styles. 
Added a storybook story as well.
=> Fix CSP: remove styles in `innerHTML`

packages/react-google-maps-api/src/utils/prevent-google-fonts.ts
It appears that Google Maps started making requests for the `Google Sans Text` font, in addition to/instead of `Roboto`.
Just trying to make `preventGoogleFontsLoading` behave as expected — see #2981
=> Prevent 'Google Sans Text' font download

packages/react-google-maps-api-infobox/src/InfoBox.tsx, packages/react-google-maps-api-marker-clusterer/src/ClusterIcon.tsx
`addDomListener` was deprecated in Maps JavaScript API [V3.48.9](https://developers.google.com/maps/documentation/javascript/releases#3.48.9) and produces console warnings. This PR replaces usages of `addDomListener` with `addListener` which has LTS.
=> Replaces deprecated addDomListener with addListener

packages/react-google-maps-api/package.json
Currently the main branch specifies React 18+ as a peer dependency. The issue comes up when running `npm install` as one must use `--legacy-peer-deps` to override the present limited peerDependency if using an earlier version of React. This patch extends the package.json specification to include 16.8 and 17, which both support hooks and both run the project.
=> React hooks are available in React 16.8 through 18

packages/react-google-maps-api-marker-clusterer/src/ClusterIcon.tsx
This change will add the event listeners to the marker div element instead of using the google.maps.event.addListener().
This change should fix [#3022](https://github.com/JustFly1984/react-google-maps-api/issues/3022)
The deprecation message states what should be used instead:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/6963d81399600abb1a2ee621705a44b8b67cf212/types/google.maps/index.d.ts#L6963
=> Fixing a problem where the click event on the cluster is not fired

packages/react-google-maps-api-marker-clusterer/src/ClusterIcon.tsx
This PR adds additional fixes to https://github.com/JustFly1984/react-google-maps-api/issues/3022
Also adding changing the following:
- Fixing the the ClusterIconStyle.className not being added to the div in the first draw
- Adding width and height to the cluster image to match the provided width and height
Cluster icon events were broken, since the handler function this references the event target.
=> Fix event listeners on ClusterIcon

packages/react-google-maps-api/src/components/drawing/DrawingManager.tsx, tsconfig.json
fixed `<DrawingManagerF/>`.
`<onPolylineComplete/>` returns correct polyline completed event, previously returned polygon completed event
`<onPolygonComplete/>` returns polygon completed event instead of nothing
Fixed the bug present and showcased in this [#3033](https://github.com/JustFly1984/react-google-maps-api/issues/3033)
=> fixed DrawingManagerF onComplete event handlers

packages/react-google-maps-api/src/components/addons/InfoBox.tsx, packages/react-google-maps-api/src/components/drawing/InfoWindow.tsx
Using @react-google-maps/api for a project and for some reason, InfoWindowF onCloseClick is not firing. Went through the code and this seems like an obvious fix, althought I'm not sure if it's the only change required.
=> Fix onCloseClick of InfoWindowF not triggering

packages/react-google-maps-api/src/components/drawing/Polygon.tsx
Adds support for `paths` prop in `<PolygonF />`. Right now this field is specified in props but not used at all, this PR fixes it.
=> Support `paths` prop in functional polygon version

packages/react-google-maps-api-marker-clusterer/src/ClusterIcon.tsx, packages/react-google-maps-api-marker-clusterer/src/types.tsx
It could be useful to support HTML elements inside ClusterIcon, maybe you want to do clustering by a property and instead of showing number you show property name. 
For example, you show a marker displaying tree location - when user zooms out you cluster them based on the group (Park 1, Park 2) instead of number of trees. There it would be useful to support html so you are able to create custom wrappers.
=> Adding support for HTML elements for cluster icons

packages/react-google-maps-api-marker-clusterer/src/ClusterIcon.tsx
The positioning of the clusterer markers gets invalidated on (at least) Google Chrome because it retains the single quotation marks.
=> Solves issue with the clusterer icon being on top of each other

packages/react-google-maps-api/src/components/addons/GoogleMarkerClusterer.stories.tsx, packages/react-google-maps-api/src/components/addons/MarkerClusterer.md, packages/react-google-maps-api/src/components/addons/MarkerClusterer.stories.tsx, packages/react-google-maps-api/src/components/addons/MarkerClustererF.stories.tsx
This PR fixes issue of typescript error and eslint warning, occurring when adding marker cluster according to the documentation examples
Fixes same issues in clusterer.stories files.
=> Fix clusterer example

packages/react-google-maps-api/src/components/dom/Overlay.tsx, packages/react-google-maps-api/src/components/dom/OverlayView.stories.tsx, packages/react-google-maps-api/src/components/dom/OverlayView.tsx
As per https://github.com/JustFly1984/react-google-maps-api/pull/3106#pullrequestreview-1198656139, a breaking change was introduced where `OverlayViewF` stopped supporting the `bounds` prop, and made `position` required.
It also changed the way styles are set from assigning width/height, to using transform - though I'm not aware of any bugs that created.
This PR makes the `OverlayViewF` support the same features as `OverlayView` and closes https://github.com/JustFly1984/react-google-maps-api/issues/3114
See GIF of storybook - the red boxes already existed, the yellow one is new, using the `bounds` prop.
Cutting a patch release would be much appreciated! If that won't happen soon please LMK and I'll use my fork in the meantime.
cc @andrewdoro you may also want to review this.
=> Fix backward incompatible change in OverlayViewF

packages/react-google-maps-api/src/components/drawing/Data.md
Point was not placed in [Data](https://react-google-maps-api-docs.netlify.app/#data)  example when we click on map.
Fix example
=> Fix: Point not placed on click in `Data` example

packages/react-google-maps-api/src/GoogleMap.tsx
This commit ensures the GoogleMapState interface is exported to be used when importing the library.
I need this type to run the example on https://www.npmjs.com/package/@react-google-maps/api.
=> feat: export GoogleMapState

packages/react-google-maps-api/rollup.config.js
Currently, `react/jsx-runtime` is being inline into your bundles due to it not being marked as external. You can plainly see this in the built bundles, [React's license acts as an easy to spot annotation](https://www.runpkg.com/?@react-google-maps/api@2.17.1/dist/esm.js#14).
This bloats the bundle and makes it incompatible with Preact (see https://github.com/preactjs/preact/issues/3870), as React cannot be aliased out if it's being inlined.
=> refactor: Ensure `react/jsx-runtime` isn't inlined into bundle

packages/react-google-maps-api/src/components/drawing/DrawingManager.tsx
It was not possible to cancel the current drawingMode (polygon, etc) by passing null. The condition inside the useEffect only accepted truthy values for drawingMode, making it impossible to exit a selected drawingMode.
=> Fix bug that prevented null from being passed as a drawingMode

packages/react-google-maps-api/src/components/drawing/Polygon.tsx
Add support for two event `insert_at` and `set_at` 
Events are described in API reference but are not currently supported within the library.
I'd like to have it on one of the projects, thanks in advance for taking a look
Let me know if you want anything changed :)
https://developers.google.com/maps/documentation/javascript/reference/event#MVCArray-Events
=> Add `onEdit` to Polygon

packages/react-google-maps-api/src/components/drawing/Marker.tsx
fixes:
- https://github.com/JustFly1984/react-google-maps-api/issues/3278
- https://github.com/JustFly1984/react-google-maps-api/issues/3066
In MarkerF in https://github.com/JustFly1984/react-google-maps-api/blob/fbf7b24d48ac0030efd9930abb6d56efa64bf4fa/packages/react-google-maps-api/src/components/drawing/Marker.tsx#L180-L283 , there was only `useEffects` for some properties but not for all, which had the problem, that some property changes did not trigger re-render. Most prominent one is `icon`.
=> add useEffects in MarkerF for clickable, cursor, icon, label, opacity, shape, title, zIndex

packages/react-google-maps-api/src/utils/make-load-script-url.ts
The `make-load-script-url` file does not add `loading=async` to its script. This results in a warning that google maps api should be loaded asynchronously for optimal performance. 
Ref: https://developers.google.com/maps/documentation/javascript/overview
Issue: #3334
=> Load google maps asynchronously

packages/react-google-maps-api-gatsby-example/src/examples/example-directions.tsx, packages/react-google-maps-api-gatsby-example/src/examples/example-drawing.tsx, packages/react-google-maps-api-gatsby-example/src/examples/example-ground.tsx, packages/react-google-maps-api-gatsby-example/src/examples/example-heatmap.tsx, packages/react-google-maps-api-gatsby-example/src/examples/example-options.tsx, packages/react-google-maps-api-gatsby-example/src/examples/example-overlay-view.tsx, packages/react-google-maps-api-gatsby-example/src/examples/example-search-box.tsx, packages/react-google-maps-api-gatsby-example/src/examples/example-shapes.tsx, packages/react-google-maps-api-gatsby-example/src/examples/example-traffic.tsx, packages/react-google-maps-api-gatsby-example/src/examples/example-transit.tsx, packages/react-google-maps-api/src/LoadScript.tsx, packages/react-google-maps-api/src/__tests__/components/circle.test.tsx, packages/react-google-maps-api/src/components/addons/MarkerClusterer.tsx, packages/react-google-maps-api/src/components/directions/DirectionsRenderer.md, packages/react-google-maps-api/src/components/directions/DirectionsRenderer.tsx, packages/react-google-maps-api/src/components/dom/OverlayView.stories.tsx, packages/react-google-maps-api/src/components/drawing/Marker.tsx, packages/react-google-maps-api/src/components/places/Autocomplete.tsx, packages/react-google-maps-api/src/components/places/StandaloneSearchBox.tsx, packages/react-google-maps-api/src/docs/DocsApiKeyInput.tsx, packages/react-google-maps-api/src/docs/ScriptLoaded.tsx
This PR updates the code to eliminate some type problems with React 19 RC.
- Use `React.JSX` instead of global `JSX.`
- Use `React.ReactNode` instead of `React.ReactChild`
=> Prepare for React 19

packages/react-google-maps-api/src/components/drawing/Polygon.tsx
Currently when editing a Polygon if you add a new point and and then click the undo button the `onEdit` event does not fire indicating the return to the original path because it is a `remove_at` event. However if you move an existing point and then click the undo button the `onEdit` event _does_ fire since it is a `set_at` event. This is an inconsistent behaviour.
This is fixed by adding a `remove_at` listener to the Polygon's path in the same way as the `insert_at` and `set_at` listeners.
=> Update Polygon onEdit to include remove_at listener

packages/react-google-maps-api/src/__tests__/components/circle.test.tsx
Fixes this lint error
just introduced in #3382.
=> Fix lint error

packages/react-google-maps-api/package.json
Include React 19 in peer deps for api package, as suggested in https://github.com/JustFly1984/react-google-maps-api/pull/3382#issuecomment-2400559676.
(Note that only one package actually had React as a peer dep.)
=> Include React 19 in peer deps

packages/react-google-maps-api/src/LoadScript.tsx, packages/react-google-maps-api/src/useLoadScript.tsx
Fix type errors related to React ref for React 19
=> fix: load script type errors
